site_name: Ruina Wiki
theme: windmill
use_directory_urls: false

nav:
  - 首页: index.md
  - 作者设定集:
    - 日文原版: 
      - 概要: 作者设定集/日文原版/概要.md
      - ネス公国: 作者设定集/日文原版/ネス公国.md
      - 地理と生活: 作者设定集/日文原版/地理と生活.md
      - 歴史: 作者设定集/日文原版/歴史.md
      - 騎士と貴族: 作者设定集/日文原版/騎士と貴族.md
    - 贴吧汉化版:
      - 声明: 作者设定集/贴吧汉化版/声明.md
      - 概要: 作者设定集/贴吧汉化版/概要.md
      - 涅斯公国: 作者设定集/贴吧汉化版/涅斯公国.md
      - 地理与生活: 作者设定集/贴吧汉化版/地理与生活.md
      - 历史: 作者设定集/贴吧汉化版/历史.md
      - 骑士与贵族: 作者设定集/贴吧汉化版/骑士与贵族.md