site_name: Ruina Wiki
site_author: 'Xenolies'
theme:
  name: material
  logo: img/logo.png # logo
  favicon: img/favicon.ico  # favicon
  features:
    - navigation.sections # nav节点缩进
    - navigation.expand # 不折叠左侧nav节点
    - navigation.top # 一键回顶部    
#d6c7b5
markdown_extensions:
  - tables
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences
use_directory_urls: true

nav:
  - 首页: index.md
  - 更新记录: 更新记录.md
  - 作者设定集:
    - 日文原版:
      - 概要: 作者设定集/日文原版/概要.md
      - ネス公国: 作者设定集/日文原版/ネス公国.md
      - 地理と生活: 作者设定集/日文原版/地理と生活.md
      - 歴史: 作者设定集/日文原版/歴史.md
      - 騎士と貴族: 作者设定集/日文原版/騎士と貴族.md
    - 贴吧汉化版:
      - 声明: 作者设定集/贴吧汉化版/声明.md
      - 概要: 作者设定集/贴吧汉化版/概要.md
      - 涅斯公国: 作者设定集/贴吧汉化版/涅斯公国.md
      - 地理与生活: 作者设定集/贴吧汉化版/地理与生活.md
      - 历史: 作者设定集/贴吧汉化版/历史.md
      - 骑士与贵族: 作者设定集/贴吧汉化版/骑士与贵族.md
  - 游戏内资料整理:
    - 冒险手册 书籍: 游戏内资料整理/冒险手册_书籍/冒险手册_书籍.md